version: 2
updates:
  - package-ecosystem: npm
    directory: /Solo-Code
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /Anthem-Code
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
