import type {
  KuyBusiness,
  KuyCompetitor,
  KuyContentItem,
  KuyInsight,
  KuyLead,
} from "./types";
import {
  KUY_APLUS1_DEFAULT_BUSINESS,
  KUY_APLUS1_METRICS,
  KUY_APLUS1_PROMPT_TASKS,
} from "./aplus1";

export const DEMO_BUSINESS_ID = "demo-aplus1-growth";

export const DEMO_BUSINESSES: KuyBusiness[] = [
  {
    id: DEMO_BUSINESS_ID,
    owner_id: "demo",
    business_name: KUY_APLUS1_DEFAULT_BUSINESS.business_name,
    category: KUY_APLUS1_DEFAULT_BUSINESS.category,
    product_service: KUY_APLUS1_DEFAULT_BUSINESS.product_service,
    target_customer: KUY_APLUS1_DEFAULT_BUSINESS.target_customer,
    location: KUY_APLUS1_DEFAULT_BUSINESS.location,
    language: "both",
    main_keyword: KUY_APLUS1_DEFAULT_BUSINESS.main_keyword,
    pain_points: [...KUY_APLUS1_DEFAULT_BUSINESS.pain_points],
    goals: [...KUY_APLUS1_DEFAULT_BUSINESS.goals],
    preferred_platforms: [...KUY_APLUS1_DEFAULT_BUSINESS.preferred_platforms],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_LEADS: KuyLead[] = [
  {
    id: "lead-1",
    business_id: DEMO_BUSINESS_ID,
    platform: "TikTok",
    source_url: "https://www.tiktok.com/@example/video/portfolio-tips",
    lead_name: "นักออกแบบมือใหม่ — ถามแพลตฟอร์มโปรไฟล์",
    matched_keyword: "portfolio",
    intent: "หาแพลตฟอร์มโชว์ผลงาน",
    pain_point: "Behance คนเยอะแต่ไม่ได้งานจ้างในไทย",
    post_summary: "ถามว่ามีแอปไหนรวม portfolio + งานจ้าง",
    engagement: 620,
    lead_score: 91,
    urgency_level: "high",
    buying_signal: "ถามเปรียบเทียบแพลตฟอร์ม",
    suggested_offer: "สมัคร Aplus1 + โปรไฟล์พร้อม publish 3 ผลงาน",
    outreach_message: null,
    status: "qualified",
    tags: ["creator", "high-intent"],
    created_at: new Date().toISOString(),
  },
  {
    id: "lead-2",
    business_id: DEMO_BUSINESS_ID,
    platform: "LinkedIn",
    source_url: "https://www.linkedin.com/posts/example-hiring-designer",
    lead_name: "SME Brand — หาดีไซน์เนอร์ฟรีแลนซ์",
    matched_keyword: "จ้างดีไซน์",
    intent: "ประกาศจ้าง / หาฟรีแลนซ์",
    pain_point: "โพสต์ในกลุ่มแล้วได้คนไม่ตรงสไตล์",
    post_summary: "หาดีไซน์เนอร์ทำแบรนด์อาหาร",
    engagement: 240,
    lead_score: 86,
    urgency_level: "high",
    buying_signal: "ขอรีวิวแพลตฟอร์มจ้างงาน",
    suggested_offer: "โพสต์งานบน Aplus1 Jobs + studio collab",
    outreach_message: null,
    status: "follow_up",
    tags: ["hirer", "sme"],
    created_at: new Date().toISOString(),
  },
  {
    id: "lead-3",
    business_id: DEMO_BUSINESS_ID,
    platform: "Instagram",
    source_url: "https://www.instagram.com/p/example-studio-collab",
    lead_name: "สตูดิโอเล็ก — หาคู่คอลแลป",
    matched_keyword: "คอลแลป",
    intent: "หาพาร์ทเนอร์ร่วมงาน",
    pain_point: "ทีมเล็ก อยากหาคน motion เพิ่ม",
    post_summary: "มองหาคอลแลปงาน campaign",
    engagement: 180,
    lead_score: 82,
    urgency_level: "medium",
    buying_signal: "ถามช่องทางหาครีเอทีฟ",
    suggested_offer: "สร้าง Studio บน Aplus1 + เปิด collab request",
    outreach_message: null,
    status: "new",
    tags: ["studio"],
    created_at: new Date().toISOString(),
  },
];

export const DEMO_COMPETITORS: KuyCompetitor[] = [
  {
    id: "comp-1",
    business_id: DEMO_BUSINESS_ID,
    competitor_name: "Behance / Adobe",
    platform: "Website",
    profile_url: "https://www.behance.net/",
    category: "Portfolio network",
    followers: null,
    engagement: null,
    posting_frequency: "daily",
    top_content_angle: "showcase + case study",
    main_offer: "portfolio hosting",
    price_signal: "freemium + CC",
    strength: "brand awareness global",
    weakness: "ไม่มี marketplace จ้างงานไทยตรงๆ",
    opportunity_gap: "local hire + chat + collab",
    threat_level: "medium",
    recommended_action: "เน้น Aplus1 = portfolio + jobs + community ในไทย",
    created_at: new Date().toISOString(),
  },
  {
    id: "comp-2",
    business_id: DEMO_BUSINESS_ID,
    competitor_name: "Fastwork",
    platform: "Website",
    profile_url: "https://fastwork.co/",
    category: "Freelance marketplace",
    followers: null,
    engagement: null,
    posting_frequency: "n/a",
    top_content_angle: "price comparison",
    main_offer: "hire by category",
    price_signal: "race to bottom",
    strength: "SEO จ้างฟรีแลนซ์",
    weakness: "ไม่เน้น creative portfolio community",
    opportunity_gap: "creator brand + studio + inspire feed",
    threat_level: "high",
    recommended_action: "comparison content: creative quality vs price-only",
    created_at: new Date().toISOString(),
  },
];

export const DEMO_CONTENT: KuyContentItem[] = [
  {
    id: "content-1",
    business_id: DEMO_BUSINESS_ID,
    competitor_id: "comp-2",
    platform: "TikTok",
    content_url: "https://www.tiktok.com/@example/freelance-tips",
    content_type: "short video",
    title: "5 วิธีได้งานฟรีแลนซ์ดีไซน์",
    caption: "hook จาก pain ไม่มี portfolio โดดเด่น",
    hook: "ทำไมโพสต์ผลงานแล้วไม่มีคนทัก?",
    cta: "ลิงก์ใน bio",
    engagement: 8400,
    hashtags: ["#freelance", "#designer"],
    sentiment: "neutral",
    ai_summary: "educational + pain-first",
    why_it_worked: "relatable + short form",
    suggested_adaptation: "Aplus1: โพสต์ before/after โปรไฟล์ + งานจริงจากแพลตฟอร์ม",
    created_at: new Date().toISOString(),
  },
];

export const DEMO_INSIGHTS: KuyInsight[] = [
  {
    id: "insight-1",
    business_id: DEMO_BUSINESS_ID,
    insight_type: "customer",
    title: "Creator acquisition insight",
    summary: "Creator ใหม่ต้องการทั้งโชว์ผลงานและช่องทางได้งานจ้างในที่เดียว",
    key_findings: [
      "คำถามบ่อย: ต่างจาก Behance/Fastwork ยังไง, มีงานจริงไหม",
      "Trigger สูงเมื่อเห็น portfolio + job post จากคนไทย",
      "Pain: โปรไฟล์สวยแต่ไม่มี inbound hire",
    ],
    recommendation: "ทำคอนเทนต์เปรียบเทียบ + case study creator ที่ได้งานจาก Aplus1",
    confidence_score: 0.86,
    compliance_note: "ข้อมูลช่วยตัดสินใจ ไม่ใช่ข้อเท็จจริง 100%",
    created_at: new Date().toISOString(),
  },
];

export const DEMO_METRICS = {
  totalLeads: KUY_APLUS1_METRICS.creatorLeads + KUY_APLUS1_METRICS.hiringLeads,
  highIntentLeads: 142,
  competitors: 28,
  trendingKeywords: KUY_APLUS1_METRICS.communityKeywords,
  contentOpportunities: KUY_APLUS1_METRICS.contentAngles,
  adsOpportunities: KUY_APLUS1_METRICS.adsOpportunities,
  outreachTasks: KUY_APLUS1_METRICS.outreachDue,
  complianceHealth: KUY_APLUS1_METRICS.complianceHealth,
};

export const PROMPT_TASK_LABELS = [...KUY_APLUS1_PROMPT_TASKS];
