/** Pure helpers for sitemap generation — shared by CLI and unit tests. */

export const STUDIO_SLUGS = [
  "doi-studio",
  "lotus-lab",
  "mango-pixel",
  "inkwell-co",
  "frame-field",
  "sundaze-crafts",
  "soundwave-bkk",
  "pixel-garden",
  "yim-studio",
  "talay-creative",
];

export const STATIC_PATHS = [
  { loc: "/", priority: "1.0", changefreq: "daily" },
  { loc: "/jobs", priority: "0.9", changefreq: "daily" },
  { loc: "/advertise", priority: "0.7", changefreq: "weekly" },
  { loc: "/legal/privacy", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/terms", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/cookies", priority: "0.2", changefreq: "monthly" },
  { loc: "/legal/rights", priority: "0.2", changefreq: "monthly" },
  { loc: "/legal/ip", priority: "0.3", changefreq: "monthly" },
];

/** Routes that must never appear in the public sitemap. */
export const EXCLUDED_PATHS = ["/admin", "/auth", "/chat", "/settings"];

export function catalogUid(i) {
  const hex = i.toString(16).padStart(2, "0");
  return `00000000-0000-0000-0000-00000000a0${hex}`;
}

export function catalogProjectId(i) {
  const hex = i.toString(16).padStart(2, "0");
  return `00000000-0000-0000-0002-0000000000${hex}`;
}

export function buildSitemapUrls() {
  return [
    ...STATIC_PATHS,
    ...Array.from({ length: 20 }, (_, i) => ({
      loc: `/project/${catalogProjectId(i)}`,
      priority: "0.8",
      changefreq: "weekly",
    })),
    ...Array.from({ length: 20 }, (_, i) => ({
      loc: `/u/${catalogUid(i)}`,
      priority: "0.7",
      changefreq: "weekly",
    })),
    ...STUDIO_SLUGS.map((slug) => ({
      loc: `/s/${slug}`,
      priority: "0.6",
      changefreq: "weekly",
    })),
  ];
}

export function buildSitemapXml(base) {
  const normalizedBase = base.replace(/\/$/, "");
  const urls = buildSitemapUrls();
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — run: npm run sitemap:gen -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${normalizedBase}${u.loc}</loc>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;
}
