/** Pure helpers for sitemap generation — shared by CLI and unit tests. */

/**
 * Public static routes that are indexable under launch-minimal.
 * Do not list launch-hidden paths (/jobs, /advertise, /community, /s/*, …).
 */
export const STATIC_PATHS = [
  { loc: "/", priority: "1.0", changefreq: "daily" },
  { loc: "/legal/privacy", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/terms", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/cookies", priority: "0.2", changefreq: "monthly" },
  { loc: "/legal/rights", priority: "0.2", changefreq: "monthly" },
  { loc: "/legal/ip", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/community", priority: "0.4", changefreq: "monthly" },
  { loc: "/legal/copyright-report", priority: "0.2", changefreq: "monthly" },
];

/** Seed studio slugs — only included when full-product sitemap mode is on. */
export const STUDIO_SLUGS = [
  "doi-studio",
  "lotus-lab",
  "mango-pixel",
  "inkwell-co",
  "frame-field",
  "sundaze-crafts",
  "soundwave-bkk",
  "pixel-garden",
  "yim-studio",
  "talay-creative",
];

/** Routes that must never appear in the public sitemap. */
export const EXCLUDED_PATHS = [
  "/admin",
  "/auth",
  "/chat",
  "/settings",
  "/notifications",
  "/portfolio/manage",
  "/earnings",
  "/verify",
];

/** Catalog project IDs present in seed (0x00–0x45). */
export const CATALOG_PROJECT_COUNT = 70;
/** Catalog profile IDs present in seed (a000–a01f). */
export const CATALOG_PROFILE_COUNT = 32;

export function catalogUid(i) {
  const hex = i.toString(16).padStart(2, "0");
  return `00000000-0000-0000-0000-00000000a0${hex}`;
}

export function catalogProjectId(i) {
  const hex = i.toString(16).padStart(2, "0");
  return `00000000-0000-0000-0002-0000000000${hex}`;
}

/**
 * @param {{
 *   fullProduct?: boolean,
 *   projectIds?: string[],
 *   profileUserIds?: string[],
 *   vanityHandles?: string[],
 *   seriesIds?: string[],
 * }} [opts]
 */
export function buildSitemapUrls(opts = {}) {
  const fullProduct = opts.fullProduct === true;
  const projectIds =
    opts.projectIds?.length > 0
      ? opts.projectIds
      : Array.from({ length: CATALOG_PROJECT_COUNT }, (_, i) => catalogProjectId(i));
  const profileUserIds =
    opts.profileUserIds?.length > 0
      ? opts.profileUserIds
      : Array.from({ length: CATALOG_PROFILE_COUNT }, (_, i) => catalogUid(i));
  const vanityHandles = (opts.vanityHandles || []).filter(Boolean);
  const seriesIds = opts.seriesIds || [];

  const staticPaths = [...STATIC_PATHS];
  if (fullProduct) {
    staticPaths.splice(1, 0,
      { loc: "/jobs", priority: "0.9", changefreq: "daily" },
      { loc: "/advertise", priority: "0.7", changefreq: "weekly" },
      { loc: "/community", priority: "0.8", changefreq: "daily" },
      { loc: "/research", priority: "0.5", changefreq: "weekly" },
    );
  }

  const urls = [
    ...staticPaths,
    ...projectIds.map((id) => ({
      loc: `/project/${id}`,
      priority: "0.8",
      changefreq: "weekly",
    })),
    ...profileUserIds.map((id) => ({
      loc: `/u/${id}`,
      priority: "0.7",
      changefreq: "weekly",
    })),
    ...vanityHandles.map((handle) => ({
      loc: `/@${String(handle).replace(/^@/, "")}`,
      priority: "0.75",
      changefreq: "weekly",
    })),
    ...seriesIds.map((id) => ({
      loc: `/series/${id}`,
      priority: "0.65",
      changefreq: "weekly",
    })),
  ];

  if (fullProduct) {
    urls.push(
      ...STUDIO_SLUGS.map((slug) => ({
        loc: `/s/${slug}`,
        priority: "0.6",
        changefreq: "weekly",
      })),
    );
  }

  return urls;
}

export function buildSitemapXml(base, opts = {}) {
  const normalizedBase = base.replace(/\/$/, "");
  const urls = buildSitemapUrls(opts);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — run: npm run sitemap:gen -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${normalizedBase}${u.loc}</loc>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;
}
