/** Pure helpers for A+ Vault sitemap generation. */

/** Only indexable public pages — exclude private alpha app routes. */
export const STATIC_PATHS = [
  { loc: "/legal", priority: "0.4", changefreq: "monthly" },
];

/** Routes that must never appear in the public sitemap. */
export const EXCLUDED_PATHS = ["/vault", "/demo", "/api"];

export function buildSitemapUrls() {
  return [...STATIC_PATHS];
}

export function buildSitemapXml(base) {
  const normalizedBase = base.replace(/\/$/, "");
  const urls = buildSitemapUrls();
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs — run: npm run sitemap:gen -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${normalizedBase}${u.loc}</loc>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;
}

export function buildRobotsTxt(base) {
  const normalizedBase = base.replace(/\/$/, "");
  return [
    "User-agent: *",
    "Allow: /legal",
    "Disallow: /vault",
    "Disallow: /demo",
    "Disallow: /api/",
    "",
    `Sitemap: ${normalizedBase}/sitemap.xml`,
    "",
  ].join("\n");
}

export function buildLlmsTxt(base) {
  const normalizedBase = base.replace(/\/$/, "");
  return `# A+ Vault

> Private creative reference vault for the Aplus ecosystem — save, organize, and revisit creative references.

## Public pages

- [Legal Center](${normalizedBase}/legal): Privacy, copyright, acceptable use, extension privacy, and data rights (alpha draft)

## Private alpha (not indexed)

- [Vault workspace](${normalizedBase}/vault): Login required — private reference library
- [Demo guide](${normalizedBase}/demo): Private alpha tester instructions

## Related products

- [Aplus1](https://aplus1.app): Creative community showcase
- [So1o Freelancer](https://solofreelancer.com): Freelancer back office
`;
}
