# an1hem — static SPA behind nginx (VPS / Docker Compose)

FROM node:22-bookworm-slim AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_SO1O_APP_URL=https://localhost
ARG VITE_LEGAL_WEBSITE
ARG VITE_OPS_HUB_URL=
ARG VITE_DEMO_MODE=false
ARG VITE_DEMO_SUPABASE_URL
ARG VITE_DEMO_SUPABASE_PUBLISHABLE_KEY

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID \
    VITE_SO1O_APP_URL=$VITE_SO1O_APP_URL \
    VITE_LEGAL_WEBSITE=$VITE_LEGAL_WEBSITE \
    VITE_OPS_HUB_URL=$VITE_OPS_HUB_URL \
    VITE_DEMO_MODE=$VITE_DEMO_MODE \
    VITE_DEMO_SUPABASE_URL=$VITE_DEMO_SUPABASE_URL \
    VITE_DEMO_SUPABASE_PUBLISHABLE_KEY=$VITE_DEMO_SUPABASE_PUBLISHABLE_KEY

RUN npm run build

FROM nginx:1.27-alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/ >/dev/null || exit 1
