import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { User, Save, LogOut, Shield, CheckCircle2, Loader2, Briefcase, MapPin, AlertTriangle } from "lucide-react";
import { BackButton } from "@/components/ui/BackButton";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useAuth } from "@/hooks/useAuth";
import { useProfile, useUpdateProfile } from "@/hooks/useProfile";
import { profileSchema, experienceItemSchema } from "@/lib/validators";
import type { ExperienceItem } from "@/lib/validators";
import ExperienceEditor from "@/components/profile/ExperienceEditor";
import SkillsEditor from "@/components/profile/SkillsEditor";
import ContactEditor from "@/components/profile/ContactEditor";
import { isReservedPublicHandle } from "@/lib/reservedHandles";
import { z } from "zod";
import PageLoader from "@/components/ui/PageLoader";
import { HttpErrorPage } from "@/components/HttpErrorPage";
import { supabase } from "@/integrations/supabase/client";
import { useIsAdmin } from "@/hooks/useIsAdmin";
import { SettingsPreferencesSection } from "@/components/settings/SettingsPreferencesSection";
import { ChangePasswordSection } from "@/components/settings/ChangePasswordSection";
import { EmailNotificationSection } from "@/components/settings/EmailNotificationSection";
import { cn } from "@/lib/utils";
import { useUsernameAvailability, normalizeUsername } from "@/hooks/useUsernameAvailability";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

const settingsFormSchema = profileSchema.pick({
  displayName: true,
  username: true,
  bio: true,
  role: true,
  location: true,
  email: true,
  phone: true,
  website: true,
  lineId: true,
  facebook: true,
  instagram: true,
  skills: true,
  experience: true,
  notifyEmail: true,
  notifyHire: true,
  notifyCollab: true,
});

type SettingsFormInput = z.infer<typeof settingsFormSchema>;

const parseExperience = (raw: unknown): ExperienceItem[] =>
  Array.isArray(raw) ? (raw as ExperienceItem[]) : [];

const parseSkills = (raw: unknown): string[] =>
  Array.isArray(raw) ? raw.filter((s): s is string => typeof s === "string") : [];

const empty: SettingsFormInput = {
  displayName: "",
  username: "",
  bio: "",
  role: "",
  location: "",
  email: "",
  phone: "",
  website: "",
  lineId: "",
  facebook: "",
  instagram: "",
  skills: [],
  experience: [],
  notifyEmail: true,
  notifyHire: true,
  notifyCollab: true,
};

const SettingsPage = () => {
  const navigate = useNavigate();
  const { user, loading: authLoading } = useAuth();
  const { data: profile, isLoading, isError } = useProfile(user?.id);
  const updateMut = useUpdateProfile(user?.id);
  const { data: isAdmin } = useIsAdmin();

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    toast.success("ออกจากระบบแล้ว");
    navigate("/");
  };

  const [form, setForm] = useState<SettingsFormInput>(empty);
  const [debouncedUsername, setDebouncedUsername] = useState("");
  const [usernameConfirmOpen, setUsernameConfirmOpen] = useState(false);
  const [pendingSave, setPendingSave] = useState<SettingsFormInput | null>(null);

  useEffect(() => {
    const timer = window.setTimeout(() => setDebouncedUsername(normalizeUsername(form.username)), 400);
    return () => window.clearTimeout(timer);
  }, [form.username]);

  const normalizedUsername = normalizeUsername(form.username);
  const savedUsername = normalizeUsername(profile?.username ?? "");
  const usernameUnchanged = normalizedUsername === savedUsername;
  const isAutoGeneratedUsername =
    !!profile?.user_id &&
    savedUsername.length > 7 &&
    savedUsername.endsWith(`_${profile.user_id.replace(/-/g, "").slice(0, 6)}`);
  const {
    data: usernameAvailability,
    isFetching: usernameChecking,
  } = useUsernameAvailability(debouncedUsername, user?.id);
  const usernameReserved = normalizedUsername.length >= 2 && isReservedPublicHandle(normalizedUsername);
  const usernameTaken =
    !usernameUnchanged &&
    !!usernameAvailability?.taken &&
    !usernameAvailability?.reserved;
  const usernamePending =
    normalizedUsername.length >= 2 &&
    !usernameUnchanged &&
    debouncedUsername !== normalizedUsername;
  const usernameInvalid = normalizedUsername.length > 0 && !/^[a-z0-9_.]+$/.test(normalizedUsername);
  const canSave = useMemo(() => {
    if (usernameUnchanged) return true;
    return !(
      usernameInvalid ||
      usernameReserved ||
      usernameTaken ||
      usernamePending ||
      usernameChecking
    );
  }, [
    usernameUnchanged,
    usernameInvalid,
    usernameReserved,
    usernameTaken,
    usernamePending,
    usernameChecking,
  ]);

  useEffect(() => {
    if (!authLoading && !user) navigate("/auth?redirect=/settings");
  }, [authLoading, user, navigate]);

  useEffect(() => {
    if (window.location.hash !== "#profile-about") return;
    const timer = window.setTimeout(() => {
      document.getElementById("profile-about")?.scrollIntoView({ behavior: "smooth", block: "start" });
    }, 150);
    return () => window.clearTimeout(timer);
  }, [profile]);

  useEffect(() => {
    if (profile) {
      setForm({
        displayName: profile.display_name ?? "",
        username: profile.username ?? "",
        bio: profile.bio ?? "",
        role: profile.role ?? "",
        location: profile.location ?? "",
        email: profile.email ?? user?.email ?? "",
        phone: profile.phone ?? "",
        website: profile.website ?? "",
        lineId: profile.line_id ?? "",
        facebook: profile.facebook ?? "",
        instagram: profile.instagram ?? "",
        skills: parseSkills(profile.skills),
        experience: parseExperience(profile.experience),
        notifyEmail: profile.notify_email ?? true,
        notifyHire: profile.notify_hire ?? true,
        notifyCollab: (profile as { notify_collab?: boolean }).notify_collab ?? true,
      });
    }
  }, [profile, user]);

  const update = <K extends keyof SettingsFormInput>(k: K, v: SettingsFormInput[K]) =>
    setForm((f) => ({ ...f, [k]: v }));

  const persistProfile = async (payload: SettingsFormInput, usernameChanged: boolean) => {
    try {
      await updateMut.mutateAsync(payload);
      setUsernameConfirmOpen(false);
      setPendingSave(null);
      toast.success("บันทึกสำเร็จ", {
        description: usernameChanged
          ? `ลิงก์โปรไฟล์ใหม่: /@${normalizeUsername(payload.username)}`
          : "ข้อมูลโปรไฟล์ของคุณถูกอัปเดตแล้ว",
      });
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : "บันทึกไม่สำเร็จ");
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    const cleanedExperience = form.experience
      .map((it) => ({
        title: it.title.trim(),
        company: (it.company ?? "").trim(),
        period: (it.period ?? "").trim(),
        description: (it.description ?? "").trim(),
      }))
      .filter((it) => it.title);
    for (const item of cleanedExperience) {
      const parsedItem = experienceItemSchema.safeParse(item);
      if (!parsedItem.success) {
        toast.error(parsedItem.error.issues[0]?.message ?? "ข้อมูลประสบการณ์ไม่ถูกต้อง");
        return;
      }
    }
    const payload = { ...form, experience: cleanedExperience };
    const parsed = settingsFormSchema.safeParse(payload);
    if (!parsed.success) {
      toast.error(parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง");
      return;
    }
    if (!canSave) return;
    if (!usernameUnchanged) {
      setPendingSave(parsed.data);
      setUsernameConfirmOpen(true);
      return;
    }
    await persistProfile(parsed.data, false);
  };

  if (authLoading || isLoading) {
    return <PageLoader />;
  }

  if (isError || !profile) {
    return <HttpErrorPage kind="500" homeTo="/portfolio" />;
  }

  return (
    <div className="min-h-screen bg-app-ambient">
      <div className="sticky top-0 z-20 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <BackButton />
          <span className="text-sm font-medium text-foreground">ตั้งค่าบัญชี</span>
          <span className="w-12" />
        </div>
      </div>

      <div className="bg-gradient-to-b from-primary/10 via-background to-background">
        <div className="max-w-3xl mx-auto px-4 pt-8 pb-6">
          <h1 className="text-3xl md:text-4xl font-medium text-foreground">
            ตั้งค่า<span className="text-primary">โปรไฟล์</span>ของคุณ
          </h1>
          <p className="mt-2 text-sm text-muted-foreground">ปรับแต่งข้อมูลที่จะแสดงบนหน้าผลงานและคำขอจ้างงาน</p>
        </div>
      </div>

      <form onSubmit={handleSave} className="max-w-3xl mx-auto px-4 pb-24 space-y-6">
        <section id="profile-about" className="rounded-2xl glass-panel p-6 space-y-5 scroll-mt-24">
          <SectionTitle icon={User} title="ข้อมูลส่วนตัว" />
          <Field
            label="ชื่อที่แสดง"
            value={form.displayName}
            onChange={(v) => update("displayName", v)}
            hint="ชื่อที่คนอื่นเห็นในฟีด คอมเมนต์ และโปรไฟล์ — ไม่จำเป็นต้องไม่ซ้ำกับคนอื่น"
            id="settings-display-name"
          />
          <div>
            <label htmlFor="settings-username" className="text-sm font-medium text-foreground">
              ชื่อผู้ใช้ (username)
            </label>
            <p className="mt-0.5 text-xs text-muted-foreground">
              ใช้ในลิงก์โปรไฟล์และ @mention — ต้องไม่ซ้ำกับคนอื่น (a-z, 0-9, _ และ .)
            </p>
            <div
              className={cn(
                "mt-1 flex items-center rounded-xl bg-secondary border border-border focus-within:ring-2 focus-within:ring-primary/40",
                (usernameTaken || usernameReserved || usernameInvalid) && "border-destructive focus-within:ring-destructive/40",
              )}
            >
              <span className="pl-3 text-muted-foreground text-sm">@</span>
              <input
                id="settings-username"
                type="text"
                value={form.username}
                onChange={(e) => update("username", e.target.value.toLowerCase())}
                autoCapitalize="off"
                autoCorrect="off"
                spellCheck={false}
                className="flex-1 bg-transparent px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none"
              />
            </div>
            {normalizedUsername.length >= 2 && !usernameUnchanged && (
              <p
                className={cn(
                  "mt-1 text-xs flex items-center gap-1",
                  usernamePending || (usernameChecking && debouncedUsername === normalizedUsername)
                    ? "text-muted-foreground"
                    : usernameInvalid
                      ? "text-destructive"
                      : usernameReserved
                        ? "text-destructive"
                        : usernameTaken
                          ? "text-destructive"
                          : "text-emerald-600 dark:text-emerald-400",
                )}
              >
                {usernamePending || (usernameChecking && debouncedUsername === normalizedUsername) ? (
                  <>
                    <Loader2 className="w-3 h-3 animate-spin" /> กำลังตรวจสอบชื่อผู้ใช้…
                  </>
                ) : usernameInvalid ? (
                  "ใช้ได้เฉพาะ a-z, 0-9, _ และ ."
                ) : usernameReserved ? (
                  "ชื่อผู้ใช้นี้สงวนไว้ — ลองชื่ออื่น"
                ) : usernameTaken ? (
                  "ชื่อผู้ใช้นี้ถูกใช้แล้ว — ลองชื่ออื่น"
                ) : (
                  <>
                    <CheckCircle2 className="w-3 h-3" /> ชื่อผู้ใช้นี้ใช้ได้
                  </>
                )}
              </p>
            )}
            {isAutoGeneratedUsername && usernameUnchanged && (
              <p className="mt-1 text-xs text-muted-foreground">
                ตอนนี้ใช้ชื่อที่ระบบสร้างให้ — เปลี่ยนเป็น @username ที่จำง่ายได้ เช่น ชื่อเล่นหรือชื่อสตูดิโอ
              </p>
            )}
          </div>
          {normalizedUsername.length >= 2 && (
            <p className="text-xs text-muted-foreground -mt-2">
              ลิงก์โปรไฟล์สาธารณะ:{" "}
              <span className="text-primary font-medium">/@{normalizedUsername}</span>
            </p>
          )}
          {!usernameUnchanged && normalizedUsername.length >= 2 && canSave && (
            <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 -mt-2">
              <p className="text-xs text-foreground flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 shrink-0 text-amber-600 dark:text-amber-400 mt-0.5" />
                <span>
                  เปลี่ยนชื่อผู้ใช้แล้วลิงก์โปรไฟล์จะเปลี่ยนจาก{" "}
                  <span className="font-medium">/@{savedUsername}</span> เป็น{" "}
                  <span className="font-medium">/@{normalizedUsername}</span> — ลิงก์เก่าที่แชร์ไว้จะเปิดไม่ได้
                </span>
              </p>
            </div>
          )}
          <Field
            label="ตำแหน่ง / สาขา"
            value={form.role}
            onChange={(v) => update("role", v)}
            icon={Briefcase}
            placeholder="เช่น Graphic Designer, UX/UI"
            id="settings-role"
          />
          <Field
            label="เมือง / ที่อยู่"
            value={form.location}
            onChange={(v) => update("location", v)}
            icon={MapPin}
            placeholder="กรุงเทพฯ, ประเทศไทย"
            id="settings-location"
          />
          <div>
            <label htmlFor="settings-bio" className="text-sm font-medium text-foreground">แนะนำตัว</label>
            <textarea
              id="settings-bio"
              value={form.bio ?? ""}
              onChange={(e) => update("bio", e.target.value)}
              rows={4}
              maxLength={500}
              className="mt-1 w-full px-4 py-2.5 rounded-xl bg-secondary border border-border text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary/40 resize-none"
            />
            <p className="mt-1 text-xs text-muted-foreground">{(form.bio ?? "").length}/500 ตัวอักษร</p>
          </div>

          <div className="border-t border-border/60 pt-5 space-y-4">
            <h3 className="text-sm font-medium text-foreground">ประสบการณ์ทำงาน</h3>
            <ExperienceEditor
              value={form.experience}
              onChange={(experience) => update("experience", experience)}
            />
          </div>

          <div className="border-t border-border/60 pt-5 space-y-3">
            <h3 className="text-sm font-medium text-foreground">ความชำนาญ</h3>
            <SkillsEditor value={form.skills} onChange={(skills) => update("skills", skills)} />
          </div>

          <div className="border-t border-border/60 pt-5 space-y-3">
            <h3 className="text-sm font-medium text-foreground">ข้อมูลติดต่อ</h3>
            <ContactEditor
              value={{
                email: form.email,
                phone: form.phone,
                website: form.website,
                lineId: form.lineId,
                facebook: form.facebook,
                instagram: form.instagram,
              }}
              onChange={(patch) => setForm((f) => ({ ...f, ...patch }))}
            />
          </div>
        </section>

        <EmailNotificationSection
          value={{
            notifyEmail: form.notifyEmail,
            notifyHire: form.notifyHire,
            notifyCollab: form.notifyCollab,
          }}
          onChange={update}
        />

        <SettingsPreferencesSection />

        {user && <ChangePasswordSection user={user} />}

        {isAdmin && (
          <section className="rounded-2xl glass-panel p-6 space-y-3">
            <SectionTitle icon={Shield} title="ผู้ดูแลระบบ" />
            <p className="text-xs text-muted-foreground">เข้าถึงเครื่องมือมอนิเตอร์และจัดการทั้งระบบ</p>
            <button
              type="button"
              onClick={() => navigate("/admin")}
              className="inline-flex items-center gap-2 rounded-full bg-foreground text-background hover:bg-foreground/90 px-4 py-2 text-sm font-medium transition-colors"
            >
              <Shield className="w-4 h-4" /> เปิดหน้าแอดมิน
            </button>
          </section>
        )}

        <section className="rounded-2xl glass-panel p-6 space-y-4">
          <SectionTitle icon={LogOut} title="บัญชี" />
          <button
            type="button"
            onClick={handleSignOut}
            className="inline-flex items-center gap-2 rounded-full bg-destructive/10 hover:bg-destructive/20 text-destructive px-4 py-2 text-sm font-medium transition-colors"
          >
            <LogOut className="w-4 h-4" /> ออกจากระบบ
          </button>
        </section>


        <div className="sticky bottom-4 flex justify-end">
          <Button type="submit" size="lg" disabled={updateMut.isPending || !canSave}
            className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-full shadow-lg px-8">
            <Save className="w-4 h-4 mr-1" /> {updateMut.isPending ? "กำลังบันทึก..." : "บันทึกการเปลี่ยนแปลง"}
          </Button>
        </div>
      </form>

      <AlertDialog open={usernameConfirmOpen} onOpenChange={setUsernameConfirmOpen}>
        <AlertDialogContent className="rounded-2xl">
          <AlertDialogHeader>
            <AlertDialogTitle>ยืนยันเปลี่ยนชื่อผู้ใช้?</AlertDialogTitle>
            <AlertDialogDescription asChild>
              <div className="text-sm text-muted-foreground leading-relaxed space-y-2">
                <p>
                  ลิงก์โปรไฟล์จะเปลี่ยนจาก{" "}
                  <span className="font-medium text-foreground">/@{savedUsername}</span> เป็น{" "}
                  <span className="font-medium text-foreground">/@{normalizedUsername}</span>
                </p>
                <p>ลิงก์เก่าที่แชร์ไว้จะเปิดไม่ได้ — ชื่อที่แสดงในฟีดจะไม่เปลี่ยนตาม</p>
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={updateMut.isPending}>ยกเลิก</AlertDialogCancel>
            <AlertDialogAction
              disabled={updateMut.isPending || !pendingSave}
              className="bg-primary text-primary-foreground hover:bg-primary/90"
              onClick={(e) => {
                e.preventDefault();
                if (pendingSave) void persistProfile(pendingSave, true);
              }}
            >
              {updateMut.isPending ? "กำลังบันทึก..." : "ยืนยันเปลี่ยน"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

const SectionTitle = ({ icon: Icon, title }: { icon: React.ComponentType<{ className?: string }>; title: string }) => (
  <div className="flex items-center gap-2"><Icon className="w-5 h-5 text-primary" /><h2 className="font-semibold text-foreground">{title}</h2></div>
);

interface FieldProps {
  label: string; value: string; onChange: (v: string) => void;
  type?: string; prefix?: string; placeholder?: string; hint?: string;
  icon?: React.ComponentType<{ className?: string }>; id?: string;
}
const Field = ({ label, value, onChange, type = "text", prefix, icon: Icon, placeholder, hint, id }: FieldProps) => {
  const fieldId = id ?? `settings-${label.replace(/\s+/g, "-").toLowerCase()}`;
  return (
  <div>
    <label htmlFor={fieldId} className="text-sm font-medium text-foreground">{label}</label>
    {hint && <p className="mt-0.5 text-xs text-muted-foreground">{hint}</p>}
    <div className="mt-1 flex items-center rounded-xl bg-secondary border border-border focus-within:ring-2 focus-within:ring-primary/40">
      {Icon && <Icon className="w-4 h-4 text-muted-foreground ml-3" />}
      {prefix && <span className="pl-3 text-muted-foreground text-sm">{prefix}</span>}
      <input id={fieldId} type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}
        className="flex-1 bg-transparent px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none" />
    </div>
  </div>
  );
};

export default SettingsPage;
