import type { CreatorObject } from "@/lib/objects/taxonomy";

const now = "2026-01-01T00:00:00.000Z";

function sample(partial: Omit<CreatorObject, "sample" | "maker_name" | "maker_username" | "created_at" | "updated_at" | "gallery_urls" | "owner_id" | "status" | "reference_project_ids"> & Partial<CreatorObject>): CreatorObject {
  return {
    owner_id: "sample",
    gallery_urls: [],
    reference_project_ids: [],
    status: "Published",
    created_at: now,
    updated_at: now,
    maker_name: "สตูดิโอตัวอย่าง",
    maker_username: null,
    sample: true,
    ...partial,
  };
}

/** Layout samples shown only while no published Objects exist yet. */
export const SAMPLE_OBJECTS: CreatorObject[] = [
  sample({
    id: "sample-print",
    title: "Morning Window",
    code: "PR04",
    summary: "ภาพพิมพ์ดิจิทัลบนกระดาษฝ้าย รุ่นเปิด ขอบขาวให้ใส่กรอบได้ทันที",
    story: "พิมพ์จากไฟล์ที่คนทำคุมสีเอง แต่ละใบตรวจขอบก่อนส่ง",
    kind: "prints",
    subtype: "art-print",
    material: "paper",
    fulfillment: "ready",
    edition: "open",
    edition_label: "",
    price_thb: 890,
    lead_time: "3–5 วัน",
    cover_url: "/objects/morning-window.jpg",
    gallery_urls: ["/objects/morning-window-2.jpg"],
    finishes: [
      { name: "Warm white", hex: "#f3efe6" },
      { name: "Ink", hex: "#1c1c1c" },
    ],
    specs: [
      { label: "ขนาด", value: "30 × 40 ซม." },
      { label: "กระดาษ", value: "Cotton rag 310 แกรม" },
      { label: "เทคนิค", value: "Digital print" },
    ],
    downloads: [{ label: "ชีตสเปก", url: "#sheet" }],
    license_note: "",
  }),
  sample({
    id: "sample-light",
    title: "Line Lamp",
    code: "LT12",
    summary: "โคมตั้งโต๊ะโลหะพ่นสีด้าน ให้แสงลงพื้นโต๊ะ",
    story: "ประกอบทีละชิ้นในสตูดิโอ สายไฟเปลี่ยนได้",
    kind: "made",
    subtype: "light",
    material: "metal",
    fulfillment: "ready",
    edition: "open",
    edition_label: "",
    price_thb: 4200,
    lead_time: "2–3 สัปดาห์",
    cover_url: "/objects/line-lamp.jpg",
    gallery_urls: ["/objects/line-lamp-2.jpg"],
    finishes: [
      { name: "Sand", hex: "#c2b8a3" },
      { name: "Graphite", hex: "#3a3a3a" },
    ],
    specs: [
      { label: "วัสดุ", value: "เหล็กพ่นสี" },
      { label: "ขนาด", value: "สูง 28 ซม." },
      { label: "หลอด", value: "E14 ไม่รวมหลอด" },
    ],
    downloads: [],
    license_note: "",
  }),
  sample({
    id: "sample-chair",
    title: "Aspen Seat",
    code: "AS10S",
    summary: "ที่นั่งไม้หมุน เบาะผ้าถอดเปลี่ยนได้",
    story: "สัดส่วนเตี้ย ใช้เป็นเก้าอี้อ่านหนังสือข้างหน้าต่าง",
    kind: "made",
    subtype: "furniture",
    material: "wood",
    fulfillment: "preorder",
    edition: "limited",
    edition_label: "12 / 40",
    price_thb: 18600,
    lead_time: "6–8 สัปดาห์",
    cover_url: "/objects/aspen-seat.jpg",
    gallery_urls: ["/objects/aspen-seat-2.jpg"],
    finishes: [
      { name: "Oak", hex: "#d8c3a5" },
      { name: "Ink fabric", hex: "#243044" },
    ],
    specs: [
      { label: "โครงสร้าง", value: "ไม้จริงและไม้อัด" },
      { label: "เบาะ", value: "ผ้า ถอดซักได้" },
      { label: "ขนาด", value: "กว้าง 68 ซม. สูง 68 ซม." },
    ],
    downloads: [{ label: "แบบขนาด", url: "#sheet" }],
    license_note: "",
  }),
  sample({
    id: "sample-vessel",
    title: "Low Bowl",
    code: "CR03",
    summary: "ชามเซรามิกเตี้ย เคลือบด้าน ใช้วางของบนโต๊ะ",
    story: "เผาในรอบเล็ก สีเคลือบต่างกันเล็กน้อยทุกใบ",
    kind: "made",
    subtype: "object",
    material: "ceramic",
    fulfillment: "ready",
    edition: "unique",
    edition_label: "1/1",
    price_thb: 1600,
    lead_time: "พร้อมส่ง",
    cover_url: "/objects/low-bowl.jpg",
    gallery_urls: ["/objects/low-bowl-2.jpg"],
    finishes: [{ name: "Clay", hex: "#c4a484" }],
    specs: [
      { label: "วัสดุ", value: "สโตนแวร์" },
      { label: "ขนาด", value: "เส้นผ่านศูนย์กลาง 18 ซม." },
    ],
    downloads: [],
    license_note: "",
  }),
  sample({
    id: "sample-zine",
    title: "Field Notes 03",
    code: "ED03",
    summary: "ซีนภาพถ่าย 36 หน้า เข้าเล่มด้าย รอบพิมพ์จำกัด",
    story: "รวมภาพเดินเท้าในเมืองรอบที่สาม",
    kind: "prints",
    subtype: "photo",
    material: "paper",
    fulfillment: "ready",
    edition: "limited",
    edition_label: "80",
    price_thb: 450,
    lead_time: "2–4 วัน",
    cover_url: "/objects/field-notes.jpg",
    gallery_urls: ["/objects/field-notes-2.jpg"],
    finishes: [{ name: "Natural", hex: "#efe6d6" }],
    specs: [
      { label: "หน้า", value: "36" },
      { label: "ขนาด", value: "A5" },
      { label: "เข้าเล่ม", value: "ด้าย" },
    ],
    downloads: [],
    license_note: "",
  }),
  sample({
    id: "sample-art-toy",
    title: "Soft Companion",
    code: "AT07",
    summary: "ซอฟุบิสีทราย ผลิตจำกัด 30 ชิ้น",
    story: "หล่อจากแม่พิมพ์ในสตูดิโอ แต่ละตัวตรวจตาดำก่อนส่ง",
    kind: "art-toy",
    subtype: "sofubi",
    material: "mixed",
    fulfillment: "preorder",
    edition: "limited",
    edition_label: "30",
    price_thb: 2800,
    lead_time: "3–4 สัปดาห์",
    cover_url: "/objects/art-toy.jpg",
    gallery_urls: ["/objects/art-toy-2.jpg"],
    finishes: [{ name: "Sand", hex: "#e6dfd2" }],
    specs: [
      { label: "วัสดุ", value: "ซอฟุบิ" },
      { label: "ขนาด", value: "สูง 15 ซม." },
    ],
    downloads: [],
    license_note: "",
  }),
  sample({
    id: "sample-template",
    title: "Proposal Kit",
    code: "FL02",
    summary: "เทมเพลตใบเสนอราคาและหน้าปกโปรเจกต์ใน Figma",
    story: "โครงที่ใช้ในสตูดิโอจริง ปรับสีและตัวหนังสือได้",
    kind: "files",
    subtype: "template",
    material: "figma",
    fulfillment: "download",
    edition: "open",
    edition_label: "",
    price_thb: 790,
    lead_time: "ได้ไฟล์ทันที",
    cover_url: "/objects/proposal-kit.jpg",
    gallery_urls: ["/objects/proposal-kit-2.jpg"],
    finishes: [],
    specs: [
      { label: "โปรแกรม", value: "Figma" },
      { label: "ในแพ็ก", value: "หน้าปก ใบเสนอราคา สไลด์สั้น" },
      { label: "ไลเซนส์", value: "ใช้ในสตูดิโอผู้ซื้อ ห้ามนำไปขายต่อเป็นเทมเพลต" },
    ],
    downloads: [{ label: "รายการไฟล์", url: "#sheet" }],
    license_note: "ใช้ในงานของตัวเองและลูกค้าตัวเอง ห้ามแจกจ่ายไฟล์ต้นฉบับ",
  }),
];

export function findSampleObject(id: string): CreatorObject | null {
  return SAMPLE_OBJECTS.find((item) => item.id === id) ?? null;
}
