import type { CvLanguageLevel, CvLanguageName, EducationDegree } from "@/lib/profileCv";
import type { ExperienceEmploymentType } from "@/lib/validators";
import {
  PROFILE_ADDRESS_EDITOR_COPY_TH,
  type ProfileAddressEditorCopy,
} from "@/lib/profileAddress";

export type AboutEditLang = "th" | "en";

export const ABOUT_EDIT_LANG_KEY = "aplus1-about-edit-lang";

const en = {
  pageTitle: "Edit About Me",
  pageHint: "Save in the section stays here — top-right Save returns to About Me",
  save: "Save",
  saving: "Saving...",
  saved: "About Me saved",
  savedStay: "Saved — you can keep editing",
  saveFailed: "Could not save",
  invalidEmail: "Enter a valid email",
  invalidPhone: "Enter a valid Thai mobile number",
  langSwitch: "Language",
  groupProfile: "Profile",
  groupWork: "Work",
  groupBackground: "Background",
  identity: "Identity",
  details: "Personal details",
  detailsHint: "Optional — nothing here appears on your CV until you tick “Show on CV”.",
  projects: "Selected work",
  references: "References",
  cvLangTitle: "CV language",
  cvLangHint: "Headings, months and labels on the CV and PDF. The text you wrote is not translated.",
  nameEn: "English name",
  nameEnPh: "e.g. Somchai Jaidee",
  nameEnHint: "Used when the CV language is English. Leave empty to reuse the name above.",
  birthDate: "Date of birth",
  nationality: "Nationality",
  nationalityPh: "e.g. Thai",
  military: "Military service",
  militaryNone: "Not specified",
  referencesHint: "Up to 3 people who can vouch for you. Hidden until you tick “Show on CV”.",
  referenceName: "Name",
  referenceRole: "Position / company",
  referenceContact: "Phone or email",
  addReference: "Add reference",
  removeLabel: "Remove",
  projectsHint: "Pick up to 3 published SAMECOR projects. If you pick none, your 3 most-viewed are used.",
  noPublishedProjects: "No published projects yet.",
  copyCvLink: "Copy CV link",
  cvLinkCopied: "CV link copied",
  livePreview: "Live preview",
  monthPh: "Month",
  yearPh: "Year",
  contact: "Contact",
  skills: "Skills",
  experience: "Experience",
  education: "Education",
  certification: "Certification",
  awards: "Awards",
  languages: "Languages",
  photo: "Photo",
  photoTitle: "About Me photo",
  photoHint: "Separate from your feed avatar — used only on About Me",
  photoFallback: "Using your profile photo as a fallback",
  photoUpload: "Upload photo",
  photoChange: "Change photo",
  photoUseAvatar: "Remove photo",
  photoShowOnCv: "Show photo on CV",
  photoShowOnCvHint: "Thai résumés usually include a photo; English ones usually don't",
  layoutTitle: "CV layout",
  layoutTwo: "Two columns",
  layoutOne: "Single column",
  layoutHint: "Applies to preview, print and PDF",
  photoAdded: "About Me photo added — Save to keep it on your profile",
  photoUseAvatarToast: "About Me photo removed — Save to keep this",
  photoFormatHint: "JPEG or PNG only — large files are compressed first",
  photoWrongType: "Use a JPEG or PNG file",
  uploadFailed: "Upload failed",
  fileTooLarge: (mb: number) => `File is larger than ${mb}MB`,
  cropTitle: "Crop About Me photo",
  cropHint: "Square crop for the document preview — does not change your feed avatar",
  zoom: "Zoom",
  cropCancel: "Cancel",
  cropUse: "Use this photo",
  cropping: "Cropping...",
  name: "Name",
  firstName: "First name",
  lastName: "Last name",
  nameHint: "Shown only on About Me — not in the feed or profile header",
  desiredPosition: "Desired position",
  desiredPositionPh: "e.g. Graphic Designer",
  dateOfBirth: "Date of birth",
  age: (n: number) => `Age ${n}`,
  dobHint: "Shown on About Me as your date of birth",
  addressUi: {
    title: "Address",
    hint: "Choose province, then district and subdistrict",
    line1: "House no. / village / alley / street",
    line1Ph: "e.g. 123/4 Moo 5 Sukhumvit 21",
    province: "Province",
    district: "District",
    subdistrict: "Subdistrict",
    postalCode: "Postal code",
    selectProvince: "Select province",
    selectDistrict: "Select district",
    selectDistrictFirst: "Select province first",
    selectSubdistrict: "Select subdistrict",
    selectSubdistrictFirst: "Select district first",
    selectPostal: "Select postal code",
    selectPostalFirst: "Select subdistrict first",
    unspecified: "Not specified",
  } satisfies ProfileAddressEditorCopy,
  aboutMe: "About me",
  aboutMePh: "e.g. Graphic designer, 4 years, packaging and print-ready files",
  aboutMeHint: "On the About Me document only — the short line on your profile card is separate",
  email: "Email",
  line: "LINE",
  phone: "Phone",
  contactHint: "Email, LINE, and phone for applications — separate from your login account",
  contactPublic: "Show email, LINE, and phone on my public profile",
  showOnCv: "Show on CV",
  addressFull: "Show full address",
  addressFullHint: "If unchecked, the CV shows district and province only",
  portfolio: "Portfolio link",
  portfolioPh: "e.g. behance.net/you",
  portfolioHint: "Optional — your own work link, like Behance. Leave blank if you don’t have one",
  website: "Website",
  skillsHint: "Work you do, e.g. package design, branding",
  software: "Design Software",
  softwareHint: "Programs you use — pick from the logo catalog",
  skillsSearch: "e.g. package design, branding, then Enter",
  skillsSearchAria: "Search skills",
  pickList: "Pick from the list",
  searchResults: "Search results",
  notInList: (q: string) => `Not in the list — press Enter to add “${q}”`,
  softwareSearch: "Search catalog programs, e.g. Photoshop",
  softwareSearchAria: "Search design software",
  pickCatalog: "Pick from the catalog",
  notInCatalog: "This program is not in the logo catalog",
  add: "Add",
  update: "Update",
  clear: "Clear",
  edit: "Edit",
  remove: "Remove",
  cancelEdit: "Cancel edit",
  present: "Present",
  start: "Start",
  end: "End",
  year: "Year",
  addExperience: "Add experience",
  editExperience: "Edit experience",
  jobTitle: "Job title *",
  company: "Company / client",
  companyPh: "e.g. WP ALL",
  employmentType: "Employment type",
  currentlyWorking: "Currently working here",
  highlights: "Highlights (up to 4) — hiring people scan these first",
  highlightPh0: "e.g. Designed packaging for 12 SKUs, print-ready",
  highlightPhNext: "Next highlight (optional)",
  experienceEmpty: "No entries yet — fill the form above, then add",
  experienceAdded: "Experience added — Save to keep it on your profile",
  experienceUpdated: "Experience updated — Save to keep it on your profile",
  experienceIncomplete: "Experience is incomplete",
  addEducation: "Add education",
  editEducation: "Edit education",
  degree: "Degree",
  selectDegree: "Select degree",
  institution: "Institution *",
  institutionPh: "e.g. KMITL",
  faculty: "Faculty",
  facultyPh: "e.g. Faculty of Architecture",
  fieldOfStudy: "Field of study",
  fieldPh: "e.g. Product Design",
  currentlyStudying: "Currently studying",
  educationEmpty: "Optional — useful for internships and full-time applications",
  educationAdded: "Education added — Save to keep it on your profile",
  educationUpdated: "Education updated — Save to keep it on your profile",
  educationIncomplete: "Incomplete education",
  addCertification: "Add certification",
  editCertification: "Edit certification",
  course: "Course or certificate *",
  coursePh: "e.g. Packaging Design Intensive",
  issuedBy: "Issued by",
  issuedByPh: "e.g. Adobe",
  certEmpty: "Optional — workshops, courses, certificates",
  certIncomplete: "Incomplete certification",
  addAward: "Add award",
  editAward: "Edit award",
  event: "Competition or event *",
  eventPh: "e.g. Young Designer Award",
  award: "Award *",
  awardPh: "e.g. First prize, packaging",
  awardsEmpty: "Optional — contests and prizes",
  awardIncomplete: "Incomplete award",
  language: "Language",
  level: "Level",
  selectLanguage: "Select language",
  selectLevel: "Select level",
  addLanguage: "Add language",
  languagesEmpty: "Select a language and level, then add",
  otherLanguagePh: "Type the language name",
  socials: "Social links",
  socialHint: "Social links — paste a URL or @username",
  other: "Other",
  channelName: "Channel name",
  channelPh: "e.g. LINE OA, Threads",
  link: "Link",
  linkPh: "https://… or @username",
  invalidLink: "Enter a valid link, or use @username",
  enterChannel: "Enter a channel name first",
  enterLink: "Enter an http:// or https:// link, or @username",
  channelExists: "That channel already has a row above — fill it there",
  maxLinks: (n: number) => `You can add up to ${n} links`,
  degreeLabels: {
    high_school: "High School",
    vocational: "Vocational Certificate",
    high_vocational: "High Vocational Diploma",
    bachelor: "Bachelor's",
    master: "Master's",
    doctorate: "Doctorate",
  } satisfies Record<EducationDegree, string>,
  languageNames: {
    Thai: "Thai",
    English: "English",
    Chinese: "Chinese",
    Cantonese: "Cantonese",
    Japanese: "Japanese",
    Korean: "Korean",
    Vietnamese: "Vietnamese",
    Indonesian: "Indonesian",
    Malay: "Malay",
    Burmese: "Burmese",
    Khmer: "Khmer",
    Lao: "Lao",
    Filipino: "Filipino",
    Hindi: "Hindi",
    Arabic: "Arabic",
    French: "French",
    German: "German",
    Spanish: "Spanish",
    Italian: "Italian",
    Portuguese: "Portuguese",
    Dutch: "Dutch",
    Russian: "Russian",
    Turkish: "Turkish",
    Swedish: "Swedish",
    Polish: "Polish",
  } satisfies Record<CvLanguageName, string>,
  languageLevels: {
    native: "Native",
    fluent: "Fluent",
    intermediate: "Intermediate",
    basic: "Basic",
  } satisfies Record<CvLanguageLevel, string>,
  employment: {
    full_time: "Full-time",
    part_time: "Part-time",
    freelance: "Freelance",
    contract: "Contract",
    owner: "Owner",
    consultant: "Consultant",
  } satisfies Record<ExperienceEmploymentType, string>,
};

export type AboutEditCopy = typeof en;

const th: AboutEditCopy = {
  pageTitle: "แก้ไขประวัติ",
  pageHint: "บันทึกในหมวดอยู่หน้าเดิม · บันทึกบนขวากลับไป About Me",
  save: "บันทึก",
  saving: "กำลังบันทึก...",
  saved: "บันทึก About Me แล้ว",
  savedStay: "บันทึกแล้ว — แก้ต่อได้",
  saveFailed: "บันทึกไม่สำเร็จ",
  invalidEmail: "ใส่อีเมลให้ถูกต้อง",
  invalidPhone: "ใส่เบอร์มือถือไทยให้ถูกต้อง",
  langSwitch: "ภาษา",
  groupProfile: "โปรไฟล์",
  groupWork: "งาน",
  groupBackground: "ประวัติ",
  identity: "ข้อมูลส่วนตัว",
  details: "รายละเอียดเพิ่มเติม",
  detailsHint: "ไม่บังคับ — ไม่แสดงบน CV จนกว่าคุณจะติ๊ก “แสดงบน CV”",
  projects: "ผลงานเด่น",
  references: "บุคคลอ้างอิง",
  cvLangTitle: "ภาษาของ CV",
  cvLangHint: "หัวข้อ เดือน และป้ายต่าง ๆ บน CV และ PDF — ข้อความที่คุณเขียนเองจะไม่ถูกแปล",
  nameEn: "ชื่อภาษาอังกฤษ",
  nameEnPh: "เช่น Somchai Jaidee",
  nameEnHint: "ใช้เมื่อ CV เป็นภาษาอังกฤษ ถ้าเว้นว่างจะใช้ชื่อด้านบน",
  birthDate: "วันเกิด",
  nationality: "สัญชาติ",
  nationalityPh: "เช่น ไทย",
  military: "สถานะทางทหาร",
  militaryNone: "ไม่ระบุ",
  referencesHint: "สูงสุด 3 คน — ไม่แสดงบน CV จนกว่าจะติ๊ก “แสดงบน CV”",
  referenceName: "ชื่อ",
  referenceRole: "ตำแหน่ง / บริษัท",
  referenceContact: "เบอร์โทรหรืออีเมล",
  addReference: "เพิ่มบุคคลอ้างอิง",
  removeLabel: "ลบ",
  projectsHint: "เลือกได้สูงสุด 3 ชิ้นจากผลงานที่เผยแพร่บน SAMECOR ถ้าไม่เลือกจะใช้ 3 ชิ้นที่มียอดดูสูงสุด",
  noPublishedProjects: "ยังไม่มีผลงานที่เผยแพร่",
  copyCvLink: "คัดลอกลิงก์ CV",
  cvLinkCopied: "คัดลอกลิงก์ CV แล้ว",
  livePreview: "พรีวิวสด",
  monthPh: "เดือน",
  yearPh: "ปี",
  contact: "ติดต่อ",
  skills: "ทักษะ",
  experience: "ประสบการณ์",
  education: "การศึกษา",
  certification: "ใบรับรอง",
  awards: "รางวัล",
  languages: "ภาษา",
  photo: "รูป",
  photoTitle: "รูป About Me",
  photoHint: "แยกจากรูปในฟีด — ใช้เฉพาะหน้า About Me",
  photoFallback: "กำลังใช้รูปโปรไฟล์แทน",
  photoUpload: "อัปโหลดรูป",
  photoChange: "เปลี่ยนรูป",
  photoUseAvatar: "ลบรูป",
  photoShowOnCv: "แสดงรูปบน CV",
  photoShowOnCvHint: "เรซูเม่ไทยนิยมใส่รูป ส่วนเรซูเม่ภาษาอังกฤษมักไม่ใส่",
  layoutTitle: "รูปแบบ CV",
  layoutTwo: "สองคอลัมน์",
  layoutOne: "คอลัมน์เดียว",
  layoutHint: "ใช้กับพรีวิว พิมพ์ และ PDF",
  photoAdded: "ใส่รูป About Me แล้ว — กดบันทึกเพื่อเก็บลงโปรไฟล์",
  photoUseAvatarToast: "ลบรูป About Me แล้ว — กดบันทึกเพื่อเก็บ",
  photoFormatHint: "รับเฉพาะ JPEG หรือ PNG — ไฟล์ใหญ่จะถูกบีบอัดก่อนอัปโหลด",
  photoWrongType: "ใช้ไฟล์ JPEG หรือ PNG เท่านั้น",
  uploadFailed: "อัปโหลดไม่สำเร็จ",
  fileTooLarge: (mb: number) => `ไฟล์ใหญ่เกิน ${mb}MB`,
  cropTitle: "ครอปรูป About Me",
  cropHint: "ครอปสี่เหลี่ยมสำหรับเอกสาร — ไม่เปลี่ยนรูปในฟีด",
  zoom: "ซูม",
  cropCancel: "ยกเลิก",
  cropUse: "ใช้รูปนี้",
  cropping: "กำลังครอป...",
  name: "ชื่อ",
  firstName: "ชื่อ",
  lastName: "นามสกุล",
  nameHint: "โชว์เฉพาะหน้า About Me — ไม่ขึ้นในฟีดหรือหัวโปรไฟล์",
  desiredPosition: "ตำแหน่งที่ต้องการ",
  desiredPositionPh: "เช่น Graphic Designer",
  dateOfBirth: "วันเกิด",
  age: (n: number) => `อายุ ${n}`,
  dobHint: "โชว์เป็นวันเกิดบนหน้า About Me",
  addressUi: {
    ...PROFILE_ADDRESS_EDITOR_COPY_TH,
    hint: "เลือกจังหวัด แล้วเลือกเขตและตำบลต่ออัตโนมัติ",
  } satisfies ProfileAddressEditorCopy,
  aboutMe: "เกี่ยวกับฉัน",
  aboutMePh: "เช่น นักออกแบบกราฟิก 4 ปี ถนัดแพ็กเกจและไฟล์พิมพ์",
  aboutMeHint: "แสดงบนเอกสาร About Me เท่านั้น — บรรทัดแนะนำตัวสั้นบนการ์ดโปรไฟล์แยกต่างหาก",
  email: "อีเมล",
  line: "LINE",
  phone: "โทรศัพท์",
  contactHint: "อีเมล LINE และเบอร์สำหรับสมัครงาน — ไม่ใช่บัญชีล็อกอิน",
  contactPublic: "โชว์อีเมล LINE และเบอร์บนโปรไฟล์สาธารณะ",
  showOnCv: "โชว์บน CV",
  addressFull: "เปิดเผยที่อยู่เต็ม",
  addressFullHint: "ถ้าไม่ติก โชว์แค่เขตกับจังหวัด",
  portfolio: "ลิงก์พอร์ตโฟลิโอ",
  portfolioPh: "เช่น behance.net/you",
  portfolioHint: "ไม่บังคับ — ใส่ลิงก์พอร์ตของตัวเอง เช่น Behance ถ้าไม่มีก็เว้นว่างได้",
  website: "เว็บไซต์",
  skillsHint: "งานที่ทำ เช่น ออกแบบแพ็กเกจ ทำแบรนด์",
  software: "โปรแกรมออกแบบ",
  softwareHint: "โปรแกรมที่ใช้ — เลือกจากแคตตาล็อกโลโก้",
  skillsSearch: "เช่น ออกแบบแพ็กเกจ, แบรนด์ แล้วกด Enter",
  skillsSearchAria: "ค้นหาทักษะ",
  pickList: "เลือกจากรายการ",
  searchResults: "ผลการค้นหา",
  notInList: (q: string) => `ไม่อยู่ในรายการ — กด Enter เพื่อเพิ่ม “${q}”`,
  softwareSearch: "ค้นหาโปรแกรม เช่น Photoshop",
  softwareSearchAria: "ค้นหาโปรแกรมออกแบบ",
  pickCatalog: "เลือกจากแคตตาล็อก",
  notInCatalog: "โปรแกรมนี้ไม่อยู่ในแคตตาล็อกโลโก้",
  add: "เพิ่ม",
  update: "อัปเดต",
  clear: "ล้าง",
  edit: "แก้ไข",
  remove: "ลบ",
  cancelEdit: "ยกเลิกการแก้ไข",
  present: "ปัจจุบัน",
  start: "เริ่ม",
  end: "สิ้นสุด",
  year: "ปี",
  addExperience: "เพิ่มประสบการณ์",
  editExperience: "แก้ไขประสบการณ์",
  jobTitle: "ตำแหน่งงาน *",
  company: "บริษัท / ลูกค้า",
  companyPh: "เช่น WP ALL",
  employmentType: "ประเภทงาน",
  currentlyWorking: "ทำงานที่นี่อยู่",
  highlights: "ไฮไลต์ (ไม่เกิน 4 ข้อ) — คนจ้างอ่านส่วนนี้ก่อน",
  highlightPh0: "เช่น ออกแบบแพ็กเกจ 12 SKU พร้อมไฟล์พิมพ์",
  highlightPhNext: "ไฮไลต์ถัดไป (ไม่บังคับ)",
  experienceEmpty: "ยังไม่มีรายการ — กรอกด้านบนแล้วกดเพิ่ม",
  experienceAdded: "เพิ่มประสบการณ์แล้ว — กดบันทึกเพื่อเก็บลงโปรไฟล์",
  experienceUpdated: "อัปเดตประสบการณ์แล้ว — กดบันทึกเพื่อเก็บลงโปรไฟล์",
  experienceIncomplete: "ประสบการณ์ยังไม่ครบ",
  addEducation: "เพิ่มการศึกษา",
  editEducation: "แก้ไขการศึกษา",
  degree: "วุฒิ",
  selectDegree: "เลือกวุฒิ",
  institution: "สถานศึกษา *",
  institutionPh: "เช่น สจล.",
  faculty: "คณะ",
  facultyPh: "เช่น คณะสถาปัตยกรรมศาสตร์",
  fieldOfStudy: "สาขา",
  fieldPh: "เช่น การออกแบบผลิตภัณฑ์",
  currentlyStudying: "กำลังศึกษาอยู่",
  educationEmpty: "ไม่บังคับ — มีประโยชน์ตอนสมัครฝึกงานและงานประจำ",
  educationAdded: "เพิ่มการศึกษาแล้ว — กดบันทึกเพื่อเก็บลงโปรไฟล์",
  educationUpdated: "อัปเดตการศึกษาแล้ว — กดบันทึกเพื่อเก็บลงโปรไฟล์",
  educationIncomplete: "การศึกษายังไม่ครบ",
  addCertification: "เพิ่มใบรับรอง",
  editCertification: "แก้ไขใบรับรอง",
  course: "คอร์สหรือใบรับรอง *",
  coursePh: "เช่น Packaging Design Intensive",
  issuedBy: "ออกโดย",
  issuedByPh: "เช่น Adobe",
  certEmpty: "ไม่บังคับ — เวิร์กช็อป คอร์ส ใบรับรอง",
  certIncomplete: "ใบรับรองยังไม่ครบ",
  addAward: "เพิ่มรางวัล",
  editAward: "แก้ไขรางวัล",
  event: "การประกวดหรืองาน *",
  eventPh: "เช่น Young Designer Award",
  award: "รางวัล *",
  awardPh: "เช่น รางวัลที่ 1 แพ็กเกจ",
  awardsEmpty: "ไม่บังคับ — งานประกวดและรางวัล",
  awardIncomplete: "รางวัลยังไม่ครบ",
  language: "ภาษา",
  level: "ระดับ",
  selectLanguage: "เลือกภาษา",
  selectLevel: "เลือกระดับ",
  addLanguage: "เพิ่มภาษา",
  languagesEmpty: "เลือกภาษาและระดับ แล้วกดเพิ่ม",
  otherLanguagePh: "พิมพ์ชื่อภาษา",
  socials: "ลิงก์โซเชียล",
  socialHint: "ลิงก์โซเชียล — วาง URL หรือ @username",
  other: "อื่นๆ",
  channelName: "ชื่อช่องทาง",
  channelPh: "เช่น LINE OA, Threads",
  link: "ลิงก์",
  linkPh: "https://… หรือ @username",
  invalidLink: "ใส่ลิงก์ให้ถูกต้อง หรือใช้ @username",
  enterChannel: "กรอกชื่อช่องทางก่อน",
  enterLink: "ใส่ลิงก์ http:// หรือ https:// หรือ @username",
  channelExists: "ช่องทางนี้มีแถวด้านบนแล้ว — กรอกในแถวนั้นได้เลย",
  maxLinks: (n: number) => `เพิ่มได้สูงสุด ${n} ลิงก์`,
  degreeLabels: {
    high_school: "มัธยมศึกษา",
    vocational: "ปวช.",
    high_vocational: "ปวส.",
    bachelor: "ปริญญาตรี",
    master: "ปริญญาโท",
    doctorate: "ปริญญาเอก",
  },
  languageNames: {
    Thai: "ไทย",
    English: "อังกฤษ",
    Chinese: "จีน",
    Cantonese: "กวางตุ้ง",
    Japanese: "ญี่ปุ่น",
    Korean: "เกาหลี",
    Vietnamese: "เวียดนาม",
    Indonesian: "อินโดนีเซีย",
    Malay: "มาเลย์",
    Burmese: "พม่า",
    Khmer: "เขมร",
    Lao: "ลาว",
    Filipino: "ฟิลิปปินส์",
    Hindi: "ฮินดี",
    Arabic: "อาหรับ",
    French: "ฝรั่งเศส",
    German: "เยอรมัน",
    Spanish: "สเปน",
    Italian: "อิตาลี",
    Portuguese: "โปรตุเกส",
    Dutch: "ดัตช์",
    Russian: "รัสเซีย",
    Turkish: "ตุรกี",
    Swedish: "สวีเดน",
    Polish: "โปแลนด์",
  } satisfies Record<CvLanguageName, string>,
  languageLevels: {
    native: "เจ้าของภาษา",
    fluent: "คล่อง",
    intermediate: "ปานกลาง",
    basic: "พื้นฐาน",
  },
  employment: {
    full_time: "เต็มเวลา",
    part_time: "พาร์ทไทม์",
    freelance: "ฟรีแลนซ์",
    contract: "สัญญาจ้าง",
    owner: "เจ้าของกิจการ",
    consultant: "ที่ปรึกษา",
  },
};

export const ABOUT_EDIT_COPY: Record<AboutEditLang, AboutEditCopy> = { th, en };

export function readAboutEditLang(): AboutEditLang {
  try {
    const raw = localStorage.getItem(ABOUT_EDIT_LANG_KEY);
    if (raw === "en" || raw === "th") return raw;
  } catch {
    /* ignore */
  }
  return "th";
}

export function writeAboutEditLang(lang: AboutEditLang) {
  try {
    localStorage.setItem(ABOUT_EDIT_LANG_KEY, lang);
  } catch {
    /* ignore */
  }
}

export function languageDisplayName(name: string, t: AboutEditCopy): string {
  return t.languageNames[name as keyof AboutEditCopy["languageNames"]] ?? name;
}
