import { safeHttpUrl } from "@/lib/safeUrl";

// Anthem-only helpers. Kept out of safeUrl.ts because that file is vendored from Solo-Code
// (regenerated by vendor-ecosystem-shared.mjs and checked in CI).

/**
 * Social label for About/CV — show the handle only.
 * `instagram.com/passawut123` → `passawut123`
 */
export function socialDisplayId(raw?: string | null): string {
  const v = (raw ?? "").trim();
  if (!v) return "";
  const stripped = v
    .replace(/^https?:\/\//i, "")
    .replace(/^www\./i, "")
    .replace(/\/+$/, "");
  if (!stripped.includes("/")) return stripped.replace(/^@/, "");
  try {
    const u = new URL(/^[a-z][a-z0-9+.-]*:/i.test(v) ? v : `https://${v}`);
    const segs = u.pathname.split("/").filter(Boolean);
    const first = segs[0] ?? "";
    if (first && !/^profile\.php$/i.test(first) && first.toLowerCase() !== "people") {
      return decodeURIComponent(first.replace(/^@/, ""));
    }
    const id = u.searchParams.get("id");
    if (id) return id;
    if (segs.length) return decodeURIComponent(segs[segs.length - 1]!.replace(/^@/, ""));
  } catch {
    const afterHost = stripped.replace(/^[^/]+\//, "");
    const first = afterHost.split(/[/?#]/)[0] ?? "";
    if (first) return first.replace(/^@/, "");
  }
  return stripped.replace(/^@/, "");
}

/** Open external URL in a new tab only when http(s). */
export function openSafeExternalUrl(raw?: string | null): boolean {
  const url = safeHttpUrl(raw);
  if (!url) return false;
  window.open(url, "_blank", "noopener,noreferrer");
  return true;
}

/** Validate a post-login redirect path (shared Solo ↔ an1hem). */
export function safeRelativePath(raw?: string | null, fallback = "/"): string {
  if (!raw || typeof raw !== "string") return fallback;
  const s = raw.trim();
  if (!s) return fallback;
  if (!s.startsWith("/")) return fallback;
  if (s.startsWith("//") || s.startsWith("/\\") || s.startsWith("/%2f") || s.startsWith("/%5c"))
    return fallback;
  if (/[a-z][a-z0-9+.-]*:/i.test(s.slice(1, 50))) return fallback;
  return s;
}
