/** Usernames / studio slugs that must not be claimed (route or product conflicts). */
export const RESERVED_PUBLIC_HANDLES = new Set([
  "admin",
  "advertise",
  "api",
  "app",
  "auth",
  "chat",
  "collections",
  "series",
  "community",
  "contracts",
  "cookies",
  "drill",
  "earnings",
  "explore",
  "feed",
  "feedback",
  "help",
  "inspire",
  "invites",
  "jobs",
  "legal",
  "manage",
  "me",
  "new",
  "notifications",
  "portfolio",
  "privacy",
  "project",
  "referrals",
  "reports",
  "research",
  "rights",
  "s",
  "settings",
  "similar",
  "studio",
  "support",
  "terms",
  "u",
  "upgrade",
  "verify",
  "www",
]);

export function isReservedPublicHandle(handle: string): boolean {
  return RESERVED_PUBLIC_HANDLES.has(handle.trim().toLowerCase());
}
